"""Estruttura package."""

from ._attribute import Attribute, MutableAttribute, deleter, getter, setter
from ._bases import (
    BaseStructureMeta,
    BaseStructure,
    BaseUserStructure,
    BaseProxyStructure,
    BaseProxyUserStructure,
    BaseImmutableStructure,
    BaseUserImmutableStructure,
    BaseMutableStructure,
    BaseUserMutableStructure,
    BaseProxyImmutableStructure,
    BaseProxyUserImmutableStructure,
    BaseProxyMutableStructure,
    BaseProxyUserMutableStructure,
    BaseCollectionStructure,
    BaseUserCollectionStructure,
    BaseProxyCollectionStructure,
    BaseProxyUserCollectionStructure,
    BaseImmutableCollectionStructure,
    BaseUserImmutableCollectionStructure,
    BaseProxyImmutableCollectionStructure,
    BaseProxyUserImmutableCollectionStructure,
    BaseMutableCollectionStructure,
    BaseUserMutableCollectionStructure,
    BaseProxyMutableCollectionStructure,
    BaseProxyUserMutableCollectionStructure,
)
from ._dict import (
    DictStructure,
    UserDictStructure,
    ProxyDictStructure,
    ProxyUserDictStructure,
    ImmutableDictStructure,
    UserImmutableDictStructure,
    ProxyImmutableDictStructure,
    ProxyUserImmutableDictStructure,
    MutableDictStructure,
    UserMutableDictStructure,
    ProxyMutableDictStructure,
    ProxyUserMutableDictStructure,
)
from ._list import ImmutableListStructure, ListStructure, MutableListStructure
from ._relationship import Relationship, RelationshipTypesInfo
from ._set import ImmutableSetStructure, MutableSetStructure, SetStructure
from ._helpers import dict_cls, list_cls, set_cls, attribute, dict_attribute, list_attribute, set_attribute
from ._structure import (
    AttributeMap,
    ImmutableStructure,
    MutableStructure,
    Structure,
    StructureMeta,
)

__all__ = [
    "Attribute",
    "MutableAttribute",
    "getter",
    "setter",
    "deleter",
    "BaseStructureMeta",
    "BaseStructure",
    "BaseUserStructure",
    "BaseProxyStructure",
    "BaseProxyUserStructure",
    "BaseImmutableStructure",
    "BaseUserImmutableStructure",
    "BaseMutableStructure",
    "BaseUserMutableStructure",
    "BaseProxyImmutableStructure",
    "BaseProxyUserImmutableStructure",
    "BaseProxyMutableStructure",
    "BaseProxyUserMutableStructure",
    "BaseCollectionStructure",
    "BaseUserCollectionStructure",
    "BaseProxyCollectionStructure",
    "BaseProxyUserCollectionStructure",
    "BaseImmutableCollectionStructure",
    "BaseUserImmutableCollectionStructure",
    "BaseProxyImmutableCollectionStructure",
    "BaseProxyUserImmutableCollectionStructure",
    "BaseMutableCollectionStructure",
    "BaseUserMutableCollectionStructure",
    "BaseProxyMutableCollectionStructure",
    "BaseProxyUserMutableCollectionStructure",
    "AttributeMap",
    "Structure",
    "StructureMeta",
    "ImmutableStructure",
    "MutableStructure",
    "DictStructure",
    "UserDictStructure",
    "ProxyDictStructure",
    "ProxyUserDictStructure",
    "ImmutableDictStructure",
    "UserImmutableDictStructure",
    "ProxyImmutableDictStructure",
    "ProxyUserImmutableDictStructure",
    "MutableDictStructure",
    "UserMutableDictStructure",
    "ProxyMutableDictStructure",
    "ProxyUserMutableDictStructure",
    "ListStructure",
    "ImmutableListStructure",
    "MutableListStructure",
    "Relationship",
    "RelationshipTypesInfo",
    "SetStructure",
    "ImmutableSetStructure",
    "MutableSetStructure",
    "dict_cls",
    "list_cls",
    "set_cls",
    "attribute",
    "dict_attribute",
    "list_attribute",
    "set_attribute",
]
